server:
  port: 9090
spring:
  #数据库连接配置
  datasource:
    #整合成功后有： com.alibaba.druid.pool.DruidDataSource : {dataSource-1} inited
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #UTF-8这句写错了，网页不会显示 的
      url: jdbc:mysql://localhost:3306/vue?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      #druid连接池
      #type: com.alibaba.druid.pool.DruidDataSource
      username: root
      password: 123456

#thymeleaf
thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  mode: HTML
  encoding: UTF-8
  cache: false

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lccw.model    #此处写实体MODEL POJO entiy包名
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    #开启日志查sql打印





